### ISSUE TITLE
Backdoor

### ISSUE THREAD

**Issue by wireghoul** [evolutivo/asf#1]
Not sure if you've just been owned or you're being malicious, but your repo contains a backdoor as mod_api: https://github.com/evolutivo/asf/blob/17233e2fdc6b9369f236551c4083c9ac436a7049/modules/mod_api/mod_api.php

**Comment by evolutivo** [comment]
Hi, our site had been hacked. I managed to delete the hackers files. Thanks

**Comment by wireghoul** [comment]
Looks like there is a fairly large number:
media/widgetkit/widgets/slideshow/js/403.php 
administrator/j-obusfiki-2820bzv.php 
administrator/p-obusfiki-7529ccm.php 
cli/j-obusfiki--obusfiki-635bzv.php 
images/j-obusfiki-9369czv.php 
language/j-obusfiki-3564azv.php 
logs/p-obusfiki-5903bcm.php 
plugins/o-obusfiki-4366bxn.php 
https://github.com/evolutivo/asf/blob/17233e2fdc6b9369f236551c4083c9ac436a7049/index.php#L2
modules/mod_ya/temp/jquery.php 
modules/mod_ya/themes4.php 
And many many more... searching your files for "eval" is a good place to start, however, given the pervasive presence of backdoors you have mostlikely been hacked by several people several times. I would recommend restarting from a clean install and making sure you keep your Joomal and all plugins up to date.
